repos:
    - repo: local
      hooks:
          - id: rust-fmt
            name: Rust fmt
            entry: cargo fmt --all -- --check
            language: system
            types: [rust]
            pass_filenames: false

          - id: rust-clippy
            name: Rust clippy
            entry: cargo clippy --all-targets --all-features -- -D warnings
            language: system
            types: [rust]
            pass_filenames: false

          - id: rust-check
            name: Rust check
            entry: cargo check
            language: system
            types: [rust]
            pass_filenames: false
