name: Cargo Build & Test

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

env:
    CARGO_TERM_COLOR: always

jobs:
    lint:
        name: Rust project - latest
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              name: Checkout project

            - uses: dtolnay/rust-toolchain@stable
              name: Install the Rust toolchain

            - uses: Swatinem/rust-cache@v2
              name: Use cached dependencies and artifacts

            - name: Check formatting
              run: cargo fmt --check

            - name: Build
              run: cargo build --verbose

            - name: Run tests
              run: cargo test --verbose

            - name: Check linting
              run: cargo clippy -- -D warnings -W clippy::correctness -W clippy::suspicious -W clippy::complexity -W clippy::perf -W clippy::style
